# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

env:
  VERSION: ${VERSION:-0.1.0}

tasks:
  run:
    desc: Ejecuta frontend en modo desarrollo
    cmds:
      - npm run start

  test:
    desc: Ejecuta todos los tests (unit, e2e)
    cmds:
      - npm run test
      - npm run test:unit
      - npm run test:e2e

  build:
    desc: Ejecuta tests, build y construye imagen Docker
    cmds:
      - npm run test
      - npm run test:unit
      - npm run test:e2e
      - npm run build
      - docker build -f .build/Dockerfile -t spalaxdev/rms-frontend:{{.VERSION}} .
